### ISSUE TITLE
Style checker doesn't load for the new Intellij update of  2018.2.3x64 version

### ISSUE THREAD

**Issue by prateek-parashar** [Berkeley-CS61B/intellij-plugin#2]
The style checker doesn't work, after updating the Intellij IDEA to it's latest edition.
Platform - Windows 10
error message -
```
Running style checker on 1 file(s) ...
Unable to start style checker (2): 'other' has different root
```

**Comment by MeshanKhosla** [comment]
Sorry for the 5 year late reply. Plugin should work now 😂
